spring:
  # DataSource Config
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password:
      database: 0
  mybatis-plus:
    configuration:
      # 日志
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        logic-delete-field: delFlag
        logic-delete-value: 1
        logic-not-delete-value: 0
        id-type: auto

application:
  security:
    jwt:
      secret-key: cereshuzhitingnizhenbangcereshuzhitingnizhenbang
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
